services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=job'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  ms:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - '8888:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/job?autoReconnect=true&useSSL=false
    restart: on-failure
    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    driver: bridge

volumes:
  mysql-data:
