services:
  db:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=_p@ssw0rd'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - springboot-db-network

  ms:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - '8888:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/job
    restart: on-failure
    networks:
      - springboot-db-network

networks:
  springboot-db-network:
    driver: bridge

volumes:
  db-data:
