apiVersion: v1
kind: Namespace
metadata:
  name: sj-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sj-ns
  name: sj-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sj-jobs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sj-jobs
    spec:
      containers:
        - name: sj-jobs
          image: 845698241774.dkr.ecr.ap-southeast-1.amazonaws.com/sj-jobs-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


