apiVersion: v1
kind: Namespace
metadata:
  name: sj-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sj-ns
  name: sj-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sj-jobs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sj-jobs
    spec:
      containers:
        - name: sj-jobs
          image: ${IMAGE_NAME}
          env:
            - name: spring.datasource.url
              value: ${DATASOURCE_URL}

            - name: spring.datasource.username
              value: ${DATASOURCE_USER_ID}

            - name: spring.datasource.password
              value: ${DATASOURCE_SECRET}

            - name: spring.flyway.url
              value: ${DATASOURCE_URL}

            - name: spring.flyway.schemas
              value: ${DATASOURCE_USER_ID}

            - name: spring.flyway.user
              value: ${DATASOURCE_USER_ID}

            - name: spring.flyway.password
              value: ${DATASOURCE_SECRET}

          resources:
            requests:
              cpu: "150m"
              memory: "250Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"

          imagePullPolicy: Always
          ports:
            - containerPort: 8080


