apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiok-jobs-job-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiok-jobs-job-ms
  template:
    metadata:
      labels:
        app: shiok-jobs-job-ms
    spec:
      containers:
        - name: shiok-jobs-job-ms
          image: 845698241774.dkr.ecr.ap-southeast-1.amazonaws.com/sj-jobs-ms:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shiok-jobs-job-ms-service
spec:
  selector:
    app: shiok-jobs-job-ms
  ports:
    - port: 8888
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
      name: http
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shiok-jobs-job-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shiok-jobs-job-ms
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
