apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiok-jobs-job-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiok-jobs-job-ms
  template:
    metadata:
      labels:
        app: shiok-jobs-job-ms
    spec:
      containers:
        - name: shiok-jobs-job-ms
          image: andrewtan2000/shiok-jobs-job-ms:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shiok-jobs-job-ms-service
spec:
  selector:
    app: shiok-jobs-job-ms
  ports:
    - port: 8888
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
      name: http
  type: LoadBalancer
---