apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sj-ms-autoscaling
  namespace: sj-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sj-bff
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
