apiVersion: v1
kind: Service
metadata:
  namespace: sj-ns
  name: sj-jobs-service
spec:
  selector:
    app.kubernetes.io/name: sj-jobs
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
